import numpy as np

from dfttools import compute, units, fermi_boltztrap2
import xml.etree.ElementTree as ET



def parse_projwfc_log(projwfc_log_file):
    """
    Parse the log file generated by projwfc.x to get orbital information.
    
    Format: # wfc, atom, atom_symbol, wfc, l, m
    
    """
# projwfc_log_file = "../projwfc-fatbands.out"
    # proj_line = 0

    ####################################
    ###### Old method
    ####################################
    # wfc_labesl = None
    # with open(projwfc_log_file) as f:
    #     lines = f.readlines()
    #     for il, line in enumerate(lines):
    #         if "Atomic states" in line:
    #             proj_line = il + 3
    #             break
    #         pass
    #     wfc_labesl = lines[proj_line:proj_line+92]
    #     pass
    # print(wfc_labesl)

    ##############################
    ###### Oct 7, 2026
    ####################################

    wfc_labesl = []
    with open(projwfc_log_file) as f:
        lines = f.readlines()
        wfc_labesl = [line for line in lines if "state #" in line]
        pass
    # print(wfc_labesl)


    print("Format: # wfc, atom, atom_symbol, wfc, l, m")
    wfc_list = []
    for elm in wfc_labesl:
        line = elm.split()
        # print(line)
        wfc_list.append([int(line[2].split(':')[0]), int(line[4]), line[5].split('(')[1], int(line[8]),
                        int(line[9].split('=')[1]), int(line[11].split(')')[0])])
        pass

    return wfc_list




def parse_profjwc_xml(xml_path):
    """
    to parse atomic_proj.xml file generated by projwfc.x in Quantum espresso.
    Methods here will be used in combination with wavefunction labels extracted by parse_projwfc_log
    to minimize ram use and only extract specified orbital projections
    
    """
    # xml_path = "../atomic_proj.xml"
    tree = ET.parse(xml_path)
    root = tree.getroot()

    data = {}

    eigenstates = root.find('.//EIGENSTATES')

    header = root.find(".//HEADER")
    header = header.items()
    NUMBER_OF_BANDS = int(header[0][1])
    NUMBER_OF_KPOINTS = int(header[1][1])
    NUMBER_OF_SPIN_COMPONENTS = int(header[2][1])
    NUMBER_OF_ATOMIC_WFC = int(header[3][1])
    NUMBER_OF_ELECTRONS = float(header[4][1])
    FERMI_ENERGY = float(header[5][1])

    data['nbnd'] = NUMBER_OF_BANDS
    data['nkpt'] = NUMBER_OF_KPOINTS
    data['nspin'] = NUMBER_OF_SPIN_COMPONENTS
    data['nproj'] = NUMBER_OF_ATOMIC_WFC
    data['nelec'] = NUMBER_OF_ELECTRONS
    data['efermi'] = FERMI_ENERGY


    kpoints = eigenstates.findall("K-POINT")
    kpoint_list = list(map(lambda kpt: [float(x) for x in kpt.text.split()], kpoints))

    kpoint_list = np.array(kpoint_list)
    data['kpoints'] = kpoint_list


    elist = eigenstates.findall("E")
    e_list = list(map(lambda ee: [float(x) for x in ee.text.split()], elist))
    e_list = np.array(e_list)
    data['ebands'] = e_list



    projwfc_all_k = eigenstates.findall("PROJS")
    proj_data = dict()
    for ik, proj in enumerate(projwfc_all_k):
        proj_data[ik] = dict()
        wfcs = proj.findall("ATOMIC_WFC")
        for iwfc, wfc in enumerate(wfcs):
            text = wfc.text
            ab_list = [float(x) for x in text.split()]
            len(ab_list)
            prob = [ab_list[i]**2 + ab_list[i+1]**2 for i in range(0, len(ab_list), 2)]
            len(prob)
            proj_data[ik][iwfc+1] = prob
            pass
        pass

    return data, proj_data




def read_projwfc_up(filename):
    """
    reads file (*.projwfc_up) generated by projwfc.x in quantum espresso
    
    
    """

    with open(filename) as f:
        lines = f.readlines()
        pass

    # number of projection, number of irreducieble k points, number of bands
    print(lines[20])
    nproj, nkpt, nbnd = [int(s) for s in lines[20].split()]
    one_entry_count = nbnd*nkpt
    print(one_entry_count)

    label_idx = 22
    # data_start_idx = label_idx + 1
    # lines[22]

    return lines, nproj, nkpt, nbnd, one_entry_count, label_idx


def get_orbital_lines(lines, nproj, nkpt, nbnd, one_entry_count, label_idx):
    orbital_list = []
    for i in range(nproj):
        oname = lines[label_idx + one_entry_count * i + i]
        # print(oname.split('\n'))
        onameS = oname.split('\n')[0].split()
        orbital_list.append([int(onameS[0]), int(onameS[1]), onameS[2], onameS[3], int(onameS[4]), int(onameS[5]), int(onameS[6])])
        pass

    return orbital_list


def get_orbitals_for_band(lines, nproj, nkpt, nbnd, one_entry_count, label_idx, band_index):
    """
    Get all projections for band with band_index


    """
    orbital = dict()
    for projIDX in range(nproj):
        data = []
        for i in range(nkpt):
            k_index = i
            idx_line = label_idx + one_entry_count * projIDX + projIDX + band_index + k_index * nbnd
            # print(idx_line + 1)
            tmp = lines[idx_line]
            tmp = tmp.split()
            # print(tmp)
            # break
            data.append(float(tmp[-1]))
            pass
        orbital[projIDX] = np.array(data)
        pass
    return orbital





def get_block_index(orbital_list, l_index):
    block_index = [] # Fortran 1 based but block_index will contain 0-based index
    for elm in orbital_list:
        if elm[2] == 'Nb' and elm[3] == '4D' and elm[6] == l_index:
            print(elm)
            block_index.append(elm[0]-1) # converting to 0-based index
            pass
        pass
    return block_index


def get_sum_orbital(orbital, block_index):
    sum_orbital_data = np.zeros(orbital[0].shape)
    for bi in block_index:
        # print(orbital[bi].shape)
        sum_orbital_data += orbital[bi]
        pass
    return sum_orbital_data


def get_color_grid(sum_orbital_data, equiv, nk1, nk2, nk3):
    """
    equiv : can be obtained by modified fortran routine for fermi_velocity.x in QE
    """
    color_scalar = np.ones(shape=(nk1, nk2, nk3))
    for i in range(nk1):
        for j in range(nk2):
            for k in range(nk3):
                color_scalar[i,j,k] = sum_orbital_data[equiv[i,j,k]-1] # converting to 0-based index for python
                pass
            pass
        pass
    return color_scalar


def get_equiv_array(filename_equiv = "nb3s4_equiv.frmsf"):
    """
    a fermisurfer formatted file containing map of equivalent k points to get full equiv array. 
    to get full k-mesh from irreducible k-points. 
    The QE fortran routine, written by me, is needed for this to work.
    https://gitlab.com/sha314/q-e
    dev_fermi branch
    fermi_velocity.x will do the job for this
    """
    with open(filename_equiv) as f:
        lines = f.readlines()
        nk1, nk2, nk3 = [int(s) for s in lines[0].split()]
        print(nk1, nk2, nk3)

        lines = lines[6:]
        print(lines)
        pass
    lista = [int(s.split('\n')[0]) for s in lines]
    print(lista)
    equiv = np.zeros((nk1, nk2, nk3), dtype=int)
    m = 0
    for i in range(nk1):
        for j in range(nk2):
            for k in range(nk3):
                equiv[i,j,k] = lista[m] # since Fortran code index is 1 based and python is 0 based
                m += 1
                pass
            pass
        pass
    return equiv
